### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by goolissfun** [Berrysoft/Tsinghua_Auth4_Net#2]
你好，最近想写一个linux登陆校园网的脚本。请问现在校园网登陆发包结构是什么样的？

**Comment by Berrysoft** [comment]
我记得有别人写好的脚本。

[TennyZhuang/PyTUNet](https://github.com/TennyZhuang/PyTUNet)这个只能登录net，语言python

[guzhaoyuan/net.tsinghua](https://github.com/guzhaoyuan/net.tsinghua)也是net，语言bash脚本

[yuantailing/tunet-python](https://github.com/yuantailing/tunet-python)这个支持net和auth，语言python

我的主要代码在[Berrysoft.Tsinghua.Net](https://github.com/Berrysoft/ClassLibrary/tree/master/src/Berrysoft.Tsinghua.Net)，支持net和auth，语言C#。AuthHelper的注释里有js源码。

**Comment by Berrysoft** [comment]
如果没有别的问题，就把这个issue关了
